apiVersion: v1
binaryData:
  requirements.txt: Ly81aEFHa0Fid0J6QUcwQWRBQndBR3dBYVFCaUFEMEFQUUF4QUM0QU1RQXVBRGNBRFFBS0FHRUFiUUJ4QUhBQVBRQTlBRFVBTGdBeUFDNEFNQUFOQUFvQVlRQnVBRzRBYndCMEFHRUFkQUJsQUdRQUxRQjBBSGtBY0FCbEFITUFQUUE5QURBQUxnQTNBQzRBTUFBTkFBb0FZUUJ1QUhrQWFRQnZBRDBBUFFBekFDNEFOd0F1QURFQURRQUtBR0VBY2dCaEFHSUFhUUJqQUMwQWNnQmxBSE1BYUFCaEFIQUFaUUJ5QUQwQVBRQXpBQzRBTUFBdUFEQUFEUUFLQUdFQWN3Qm5BR2tBY2dCbEFHWUFQUUE5QURNQUxnQTRBQzRBTVFBTkFBb0FZUUJ6QUc0QU1RQmpBSElBZVFCd0FIUUFid0E5QUQwQU1RQXVBRFVBTGdBeEFBMEFDZ0JoQUhjQWN3QmpBR3dBYVFBOUFEMEFNUUF1QURNQU13QXVBREVBT1FBTkFBb0FZZ0JwQUd3QWJBQnBBR0VBY2dCa0FEMEFQUUEwQUM0QU1nQXVBREFBRFFBS0FHSUFiQUJwQUc0QWF3QmxBSElBUFFBOUFERUFMZ0E0QUM0QU1nQU5BQW9BWWdCdkFIUUFid0JqQUc4QWNnQmxBRDBBUFFBeEFDNEFNd0EwQUM0QU1RQXpBRGNBRFFBS0FHTUFaUUJzQUdVQWNnQjVBRDBBUFFBMUFDNEFOQUF1QURBQURRQUtBR01BWlFCeUFIUUFhUUJtQUdrQVBRQTlBRElBTUFBeUFEUUFMZ0EyQUM0QU1nQU5BQW9BWXdCbUFHWUFhUUE5QUQwQU1RQXVBREVBTmdBdUFEQUFEUUFLQUdNQWFBQmhBRzRBYmdCbEFHd0Fjd0E5QUQwQU5BQXVBREVBTGdBd0FBMEFDZ0JqQUdnQVlRQnVBRzRBWlFCc0FITUFMUUJ5QUdVQVpBQnBBSE1BUFFBOUFEUUFMZ0F5QUM0QU1BQU5BQW9BWXdCb0FHRUFjZ0JrQUdVQWRBQTlBRDBBTlFBdUFESUFMZ0F3QUEwQUNnQmpBR2dBWVFCeUFITUFaUUIwQUMwQWJnQnZBSElBYlFCaEFHd0FhUUI2QUdVQWNnQTlBRDBBTXdBdUFETUFMZ0F5QUEwQUNnQmpBR3dBYVFCakFHc0FQUUE5QURnQUxnQXhBQzRBTndBTkFBb0FZd0JzQUdrQVl3QnJBQzBBWkFCcEFHUUFlUUJ2QUhVQWJRQmxBR0VBYmdBOUFEMEFNQUF1QURNQUxnQXhBQTBBQ2dCakFHd0FhUUJqQUdzQUxRQndBR3dBZFFCbkFHa0FiZ0J6QUQwQVBRQXhBQzRBTVFBdUFERUFEUUFLQUdNQWJBQnBBR01BYXdBdEFISUFaUUJ3QUd3QVBRQTlBREFBTGdBekFDNEFNQUFOQUFvQVl3QnZBR3dBYndCeUFHRUFiUUJoQUQwQVBRQXdBQzRBTkFBdUFEWUFEUUFLQUdNQWNnQnZBRzRBTFFCa0FHVUFjd0JqQUhJQWFRQndBSFFBYndCeUFEMEFQUUF4QUM0QU5BQXVBRE1BRFFBS0FHTUFjZ0I1QUhBQWRBQnZBR2NBY2dCaEFIQUFhQUI1QUQwQVBRQTBBRElBTGdBd0FDNEFPQUFOQUFvQVl3QnpBSE1BY3dCbEFHd0FaUUJqQUhRQU1nQTlBRDBBTUFBdUFEY0FMZ0F3QUEwQUNnQmtBR2tBY3dCMEFHd0FhUUJpQUQwQVBRQXdBQzRBTXdBdUFEZ0FEUUFLQUdRQWFnQXRBR1FBWVFCMEFHRUFZZ0JoQUhNQVpRQXRBSFVBY2dCc0FEMEFQUUF5QUM0QU1nQXVBREFBRFFBS0FFUUFhZ0JoQUc0QVp3QnZBRDBBUFFBMUFDNEFNQUF1QURZQURRQUtBR1FBYWdCaEFHNEFad0J2QUMwQVl3QmxBR3dBWlFCeUFIa0FMUUJpQUdVQVlRQjBBRDBBUFFBeUFDNEFOZ0F1QURBQURRQUtBR1FBYWdCaEFHNEFad0J2QUMwQVl3QmxBR3dBWlFCeUFIa0FMUUJ5QUdVQWN3QjFBR3dBZEFCekFEMEFQUUF5QUM0QU5RQXVBREVBRFFBS0FHUUFhZ0JoQUc0QVp3QnZBQzBBWXdCdkFISUFjd0F0QUdnQVpRQmhBR1FBWlFCeUFITUFQUUE5QURRQUxnQTBBQzRBTUFBTkFBb0FaQUJxQUdFQWJnQm5BRzhBTFFCbkFISUFZUUJ3QUdnQWNRQnNBQzBBYWdCM0FIUUFQUUE5QURBQUxnQTBBQzRBTUFBTkFBb0FaQUJxQUdFQWJnQm5BRzhBTFFCbEFHNEFkZ0JwQUhJQWJ3QnVBRDBBUFFBd0FDNEFNUUF4QUM0QU1nQU5BQW9BWkFCcUFHRUFiZ0JuQUc4QUxRQm9BR1VBY2dCdkFHc0FkUUE5QUQwQU1BQXVBRE1BTGdBeEFBMEFDZ0JrQUdvQVlRQnVBR2NBYndBdEFITUFkQUJ2QUhJQVlRQm5BR1VBY3dBOUFEMEFNUUF1QURFQU5BQXVBRE1BRFFBS0FHUUFhZ0JoQUc0QVp3QnZBQzBBZEFCcEFHMEFaUUI2QUc4QWJnQmxBQzBBWmdCcEFHVUFiQUJrQUQwQVBRQTJBQzRBTVFBdUFEQUFEUUFLQUdRQWFnQmhBRzRBWndCdkFISUFaUUJ6QUhRQVpnQnlBR0VBYlFCbEFIY0Fid0J5QUdzQUxRQnpBR2tBYlFCd0FHd0FaUUJxQUhjQWRBQTlBRDBBTlFBdUFETUFMZ0F4QUEwQUNnQmtBRzRBY3dCd0FIa0FkQUJvQUc4QWJnQTlBRDBBTWdBdUFEWUFMZ0F4QUEwQUNnQmtBRzhBWXdCMUFIUUFhUUJzQUhNQVBRQTlBREFBTGdBeEFEWUFEUUFLQUdVQWJRQmhBR2tBYkFCZkFIWUFZUUJzQUdrQVpBQmhBSFFBYndCeUFEMEFQUUF5QUM0QU1RQXVBREVBRFFBS0FHWUFhUUJzQUdVQWJBQnZBR01BYXdBOUFEMEFNd0F1QURFQU5RQXVBREVBRFFBS0FFWUFiQUJoQUhNQWF3QTlBRDBBTXdBdUFEQUFMZ0F6QUEwQUNnQm5BSElBWVFCd0FHZ0FaUUJ1QUdVQUxRQmtBR29BWVFCdUFHY0Fid0E5QUQwQU13QXVBREFBTGdBd0FBMEFDZ0JvQURFQU1RQTlBRDBBTUFBdUFERUFNZ0F1QURBQURRQUtBR2dBZEFCdEFHd0FOUUJzQUdrQVlnQTlBRDBBTVFBdUFERUFEUUFLQUdnQWRBQjBBSEFBWXdCdkFISUFaUUE5QUQwQU1BQXVBREVBTXdBdUFEY0FEUUFLQUdnQWRBQjBBSEFBZEFCdkFHOEFiQUJ6QUQwQVBRQXdBQzRBTmdBdUFERUFEUUFLQUdnQWRBQjBBSEFBZUFBOUFEMEFNQUF1QURFQU9RQXVBREFBRFFBS0FHa0FaQUJ1QUdFQVBRQTlBRE1BTGdBM0FBMEFDZ0JwQUhRQWN3QmtBR0VBYmdCbkFHVUFjZ0J2QUhVQWN3QTlBRDBBTWdBdUFESUFMZ0F3QUEwQUNnQktBR2tBYmdCcUFHRUFNZ0E5QUQwQU13QXVBREVBTGdBMEFBMEFDZ0JxQUcwQVpRQnpBSEFBWVFCMEFHZ0FQUUE5QURFQUxnQXdBQzRBTVFBTkFBb0Fhd0J2QUcwQVlnQjFBRDBBUFFBMUFDNEFNd0F1QURjQURRQUtBR3dBZUFCdEFHd0FQUUE5QURVQUxnQXlBQzRBTWdBTkFBb0FiUUJoQUhJQWF3QmtBRzhBZHdCdUFDMEFhUUIwQUMwQWNBQjVBRDBBUFFBekFDNEFNQUF1QURBQURRQUtBRTBBWVFCeUFHc0FkUUJ3QUZNQVlRQm1BR1VBUFFBOUFESUFMZ0F4QUM0QU5RQU5BQW9BYlFCa0FIVUFjZ0JzQUQwQVBRQXdBQzRBTVFBdUFESUFEUUFLQUcwQVpRQnpBSE1BWVFCbkFHVUFjd0E5QUQwQU1BQXVBRGdBTGdBd0FBMEFDZ0J1QUhVQWJRQndBSGtBUFFBOUFESUFMZ0F3QUM0QU1BQU5BQW9BYndCeUFHb0Fjd0J2QUc0QVBRQTlBRE1BTGdBeEFEQUFMZ0EwQUEwQUNnQnZBSE1BWXdCeUFIa0FjQUIwQUc4QVBRQTlBREVBTGdBekFDNEFNQUFOQUFvQWNBQmhBRzRBWkFCaEFITUFQUUE5QURJQUxnQXlBQzRBTWdBTkFBb0FjQUJwQUd3QWJBQnZBSGNBUFFBOUFERUFNQUF1QURNQUxnQXdBQTBBQ2dCd0FHd0FZUUIwQUdZQWJ3QnlBRzBBWkFCcEFISUFjd0E5QUQwQU5BQXVBRElBTGdBeUFBMEFDZ0J3QUhJQWJ3QnRBSEFBZEFCZkFIUUFid0J2QUd3QWF3QnBBSFFBUFFBOUFETUFMZ0F3QUM0QU5BQTNBQTBBQ2dCd0FITUFlUUJqQUc4QWNBQm5BRElBUFFBOUFESUFMZ0E1QUM0QU9RQU5BQW9BY0FCNUFHRUFjd0J1QURFQVBRQTlBREFBTGdBMkFDNEFNQUFOQUFvQWNBQjVBR01BY0FCaEFISUFjd0JsQUhJQVBRQTlBRElBTGdBeUFESUFEUUFLQUhBQWVRQmtBR0VBYmdCMEFHa0FZd0E5QUQwQU1nQXVBRGNBTGdBekFBMEFDZ0J3QUhrQVpBQmhBRzRBZEFCcEFHTUFYd0JqQUc4QWNnQmxBRDBBUFFBeUFDNEFNUUE0QUM0QU5BQU5BQW9BVUFCNUFHY0FiUUJsQUc0QWRBQnpBRDBBUFFBeUFDNEFNUUE0QUM0QU1BQU5BQW9BY0FCNUFFZ0FZUUJ1QUdzQWJ3QTlBRDBBTUFBdUFESUFOUUF1QURBQURRQUtBSEFBZVFCb0FHRUFiZ0JyQUc4QUxRQmpBR1VBY2dCMEFIWUFZUUJzQUdrQVpBQmhBSFFBYndCeUFEMEFQUUF3QUM0QU1nQTJBQzRBTXdBTkFBb0FjQUI1QUhBQVpBQm1BRDBBUFFBMEFDNEFNZ0F1QURBQURRQUtBSEFBZVFCd0FHNEFad0E5QUQwQU1BQXVBRElBTUFBeUFESUFNQUEzQURFQU5RQXVBREFBRFFBS0FIQUFlUUIwQUdnQWJ3QnVBQzBBWWdCcEFHUUFhUUE5QUQwQU1BQXVBRFFBTGdBeUFBMEFDZ0J3QUhrQWRBQm9BRzhBYmdBdEFHTUFjZ0J2QUc0QWRBQmhBR0lBUFFBOUFETUFMZ0F4QUM0QU1BQU5BQW9BY0FCNUFIUUFhQUJ2QUc0QUxRQmtBR0VBZEFCbEFIVUFkQUJwQUd3QVBRQTlBRElBTGdBNUFDNEFNQUF1QUhBQWJ3QnpBSFFBTUFBTkFBb0FjQUI1QUhRQWFBQnZBRzRBTFFCa0FHOEFkQUJsQUc0QWRnQTlBRDBBTVFBdUFEQUFMZ0F4QUEwQUNnQndBSGtBZEFCb0FHOEFiZ0F0QUcwQWRRQnNBSFFBYVFCd0FHRUFjZ0IwQUQwQVBRQXdBQzRBTUFBdUFEa0FEUUFLQUhBQWVRQjBBSG9BUFFBOUFESUFNQUF5QURRQUxnQXhBQTBBQ2dCUUFIa0FXUUJCQUUwQVRBQTlBRDBBTmdBdUFEQUFMZ0F4QUEwQUNnQnhBSElBWXdCdkFHUUFaUUE5QUQwQU53QXVBRFFBTGdBeUFBMEFDZ0J5QUdFQWNBQnBBR1FBWmdCMUFIb0FlZ0E5QUQwQU13QXVBRGtBTGdBMEFBMEFDZ0J5QUdVQWNBQnZBSElBZEFCc0FHRUFZZ0E5QUQwQU5BQXVBRElBTGdBd0FBMEFDZ0J5QUdVQVpBQnBBSE1BUFFBOUFEVUFMZ0F3QUM0QU53QU5BQW9BY2dCbEFIRUFkUUJsQUhNQWRBQnpBRDBBUFFBeUFDNEFNd0F5QUM0QU13QU5BQW9BY2dCbEFIWUFaUUJ5QUhNQVpRQTlBRDBBTUFBdUFERUFMZ0F3QUEwQUNnQnlBR1lBWXdBekFEa0FPQUEyQUQwQVBRQXhBQzRBTlFBdUFEQUFEUUFLQUhJQWFRQmpBR2dBUFFBOUFERUFNd0F1QURjQUxnQXhBQTBBQ2dCeUFITUFZUUE5QUQwQU5BQXVBRGNBTGdBeUFBMEFDZ0J6QURNQWRBQnlBR0VBYmdCekFHWUFaUUJ5QUQwQVBRQXdBQzRBTVFBd0FDNEFNZ0FOQUFvQWN3Qm9BR1VBYkFCc0FHa0FiZ0JuQUdnQVlRQnRBRDBBUFFBeEFDNEFOUUF1QURRQURRQUtBSE1BYVFCNEFEMEFQUUF4QUM0QU1RQTJBQzRBTUFBTkFBb0Fjd0J1QUdrQVpnQm1BR2tBYndBOUFEMEFNUUF1QURNQUxnQXhBQTBBQ2dCekFIRUFiQUJ3QUdFQWNnQnpBR1VBUFFBOUFEQUFMZ0ExQUM0QU1BQU5BQW9BY3dCMEFHRUFjZ0JzQUdVQWRBQjBBR1VBUFFBOUFEQUFMZ0F6QURjQUxnQXlBQTBBQ2dCekFIWUFad0JzQUdrQVlnQTlBRDBBTVFBdUFEVUFMZ0F4QUEwQUNnQjBBR2tBYmdCNUFHTUFjd0J6QURJQVBRQTlBREVBTGdBekFDNEFNQUFOQUFvQWRBQjVBSEFBWlFCeUFEMEFQUUF3QUM0QU1RQXlBQzRBTXdBTkFBb0FkQUI1QUhBQWFRQnVBR2NBWHdCbEFIZ0FkQUJsQUc0QWN3QnBBRzhBYmdCekFEMEFQUUEwQUM0QU1RQXlBQzRBTWdBTkFBb0FkQUI2QUdRQVlRQjBBR0VBUFFBOUFESUFNQUF5QURRQUxnQXlBQTBBQ2dCMEFIb0FiQUJ2QUdNQVlRQnNBRDBBUFFBMUFDNEFNZ0FOQUFvQWRRQnFBSE1BYndCdUFEMEFQUUExQUM0QU1RQXdBQzRBTUFBTkFBb0FkUUJ5QUdrQWRBQnZBRzhBYkFCekFEMEFQUUEwQUM0QU1BQXVBRE1BRFFBS0FIVUFjZ0JzQUd3QWFRQmlBRE1BUFFBOUFESUFMZ0F5QUM0QU1RQU5BQW9BZFFCMkFHa0FZd0J2QUhJQWJnQTlBRDBBTUFBdUFETUFNQUF1QURFQURRQUtBSFlBWVFCc0FHa0FaQUIxQUhNQVBRQTlBREFBTGdBekFDNEFNQUFOQUFvQWRnQnBBRzRBWlFBOUFEMEFOUUF1QURFQUxnQXdBQTBBQ2dCMkFHa0FjZ0IwQUhVQVlRQnNBR1VBYmdCMkFEMEFQUUF5QURBQUxnQXlBRFlBTGdBeUFBMEFDZ0IzQUdFQWRBQmpBR2dBWmdCcEFHd0FaUUJ6QUQwQVBRQXdBQzRBTWdBeUFDNEFNQUFOQUFvQWR3QmpBSGNBYVFCa0FIUUFhQUE5QUQwQU1BQXVBRElBTGdBeEFETUFEUUFLQUhjQVpRQmlBR1VBYmdCakFHOEFaQUJwQUc0QVp3QnpBRDBBUFFBd0FDNEFOUUF1QURFQURRQUtBSGNBWlFCaUFITUFid0JqQUdzQVpRQjBBSE1BUFFBOUFERUFNZ0F1QURBQURRQUtBRmNBWlFCeUFHc0FlZ0JsQUhVQVp3QTlBRDBBTXdBdUFEQUFMZ0F6QUEwQUNnQjNBR2dBYVFCMEFHVUFiZ0J2QUdrQWN3QmxBRDBBUFFBMkFDNEFOZ0F1QURBQURRQUtBSGdBYUFCMEFHMEFiQUF5QUhBQVpBQm1BRDBBUFFBd0FDNEFNZ0F1QURFQU5nQU5BQW9BZUFCdEFHd0FkQUJ2QUdRQWFRQmpBSFFBUFFBOUFEQUFMZ0F4QURNQUxnQXdBQTBBQ2dBPQ==
data:
  .env: |-
    DJANGO_SETTINGS_MODULE=api_project_zoho_senitron.settings
    DJANGO_SUPERUSER_USERNAME=admin
    DJANGO_SUPERUSER_EMAIL=admin@example.com
    DJANGO_SUPERUSER_PASSWORD=admin
    LOGINUSER_USERNAME=test
    LOGINUSER_EMAIL=test@example.com
    LOGINUSER_PASSWORD=Hialeah2024*-

    ZOHO_SCOPES=ZohoInventory.items.READ,ZohoInventory.shipmentorders.READ,ZohoInventory.purchasereceives.READ,ZohoInventory.salesorders.READ
    ZOHO_INVENTORY_ITEMS_URL=https://www.zohoapis.com/inventory/v1/items
    ZOHO_INVENTORY_SHIPMENTORDERS_URL=https://www.zohoapis.com/inventory/v1/shipmentorders
    ZOHO_INVENTORY_PURCHASERECEIVES_URL=https://www.zohoapis.com/inventory/v1/purchasereceives
    ZOHO_INVENTORY_SALESORDERS_URL=https://www.zohoapis.com/inventory/v1/salesorders
    ZOHO_INVENTORY_SHIPMENTS_URL=https://inventory.zoho.com/api/v1/shipmentorders

    # ENVIRONMENT: DEV
    DB_NAME_DEV=api_zoho_senitron_qa_db
    DB_USER_DEV=postgres
    DB_PASSWORD_DEV=postgres
    DB_HOST_DEV=postgres-api-zoho-senitron
    FRONTEND_URL_DEV=http://localhost:3000
    FRONTEND_URL_DEVOPS=https://10.1.10.216
    PATH_FROM_BACKUP_DB_DEV=/app/backup

    # ENVIRONMENT: QA
    DB_NAME_QA=api_zoho_senitron_qa_db
    DB_USER_QA=postgres
    DB_PASSWORD_QA=postgres
    DB_HOST_QA=postgres-api-zoho-senitron
    FRONTEND_URL_QA=https://api-zoho-senitron.nws.home
    PATH_FROM_BACKUP_DB_QA=/app/backup

    # ENVIRONMENT: PROD
    DB_NAME_PROD=api_zoho_senitron_prod_db
    DB_USER_PROD=postgres
    DB_PASSWORD_PROD=postgres
    DB_HOST_PROD=postgres-api-zoho-senitron
    FRONTEND_URL_PROD=https://api-zoho-senitron.nws.home
    PATH_FROM_BACKUP_DB_PROD=/app/backup

    DB_PORT=5432
    DB_ENGINE=django.db.backends.postgresql

    REDIS_HOST=redis-api-zoho-senitron

    # ENVIRONMENT
    ENVIRONMENT=DEV
  Dockerfile: |-
    FROM python:3.12

    ENV PYTHONUNBUFFERED 1
    ENV PYTHONPATH=/app

    WORKDIR /app

    COPY requirements.txt /app/

    RUN pip install --upgrade pip
    RUN pip install gunicorn
    RUN pip install uvicorn
    RUN pip install -r requirements.txt

    # Instalar herramientas necesarias incluyendo cron
    RUN apt-get update && apt-get install -y wget gnupg2 lsb-release

    # Agregar repositorio de PostgreSQL
    RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list

    # Actualizar e instalar dependencias
    RUN apt-get update && apt-get install -y postgresql-client-16

    # Copia el contenido del directorio al contenedor
    COPY . /app/

    # Expose port 8000 for the Django application
    EXPOSE 8000

    # Ejecuta el script de inicialización y luego arranca Gunicorn y cron
    # CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && python init_scripts.py && gunicorn --bind 0.0.0.0:8000 api_project_zoho_senitron.asgi:application"]
    CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && python init_scripts.py && gunicorn api_project_zoho_senitron.asgi:application -w 3 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"]
  init_scripts.py: |
    import os
    import django

    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'api_project_zoho_senitron.settings')
    django.setup()

    from django.core.management import call_command
    from api_zoho.models import LoginUser

    def create_superuser():
        username = os.getenv('DJANGO_SUPERUSER_USERNAME')
        email = os.getenv('DJANGO_SUPERUSER_EMAIL')
        password = os.getenv('DJANGO_SUPERUSER_PASSWORD')

        if not LoginUser.objects.filter(username=username).exists():
            print("Creating superuser...")
            call_command('createsuperuser', '--noinput', '--username', username)
            user = LoginUser.objects.get(username=username)
            user.set_password(password)
            user.email = email
            user.save()
            print("Superuser created!")

    def create_loginuser():
        username = os.getenv('LOGINUSER_USERNAME')
        email = os.getenv('LOGINUSER_EMAIL')
        password = os.getenv('LOGINUSER_PASSWORD')

        if not LoginUser.objects.filter(username=username).exists():
            print("Creating LoginUser...")
            LoginUser.objects.create_user(username=username, email=email, password=password, is_staff=True)
            print("LoginUser created!")

    if __name__ == "__main__":
        create_superuser()
        create_loginuser()
  manage.py: |
    #!/usr/bin/env python
    """Django's command-line utility for administrative tasks."""
    import os
    import sys


    def main():
        """Run administrative tasks."""
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'api_project_zoho_senitron.settings')
        try:
            from django.core.management import execute_from_command_line
        except ImportError as exc:
            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            ) from exc
        execute_from_command_line(sys.argv)


    if __name__ == '__main__':
        main()
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-api-zoho-senitron
  name: backend-api-zoho-senitron-cm0
