apiVersion: v1
data:
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST_DEV: postgres-api-zoho-senitron
  DB_HOST_PROD: postgres-api-zoho-senitron
  DB_HOST_QA: postgres-api-zoho-senitron
  DB_NAME_DEV: api_zoho_senitron_qa_db
  DB_NAME_PROD: api_zoho_senitron_prod_db
  DB_NAME_QA: api_zoho_senitron_qa_db
  DB_PASSWORD_DEV: postgres
  DB_PASSWORD_PROD: postgres
  DB_PASSWORD_QA: postgres
  DB_PORT: "5432"
  DB_USER_DEV: postgres
  DB_USER_PROD: postgres
  DB_USER_QA: postgres
  DJANGO_SETTINGS_MODULE: api_project_zoho_senitron.settings
  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_PASSWORD: admin
  DJANGO_SUPERUSER_USERNAME: admin
  ENVIRONMENT: DEV
  FRONTEND_URL_DEV: http://localhost:3000
  FRONTEND_URL_DEVOPS: https://10.1.10.216
  FRONTEND_URL_PROD: https://api-zoho-senitron.nws.home
  FRONTEND_URL_QA: https://api-zoho-senitron.nws.home
  LOGINUSER_EMAIL: test@example.com
  LOGINUSER_PASSWORD: Hialeah2024*-
  LOGINUSER_USERNAME: test
  PATH_FROM_BACKUP_DB_DEV: /app/backup
  PATH_FROM_BACKUP_DB_PROD: /app/backup
  PATH_FROM_BACKUP_DB_QA: /app/backup
  REDIS_HOST: redis-api-zoho-senitron
  ZOHO_INVENTORY_ITEMS_URL: https://www.zohoapis.com/inventory/v1/items
  ZOHO_INVENTORY_PURCHASERECEIVES_URL: https://www.zohoapis.com/inventory/v1/purchasereceives
  ZOHO_INVENTORY_SALESORDERS_URL: https://www.zohoapis.com/inventory/v1/salesorders
  ZOHO_INVENTORY_SHIPMENTORDERS_URL: https://www.zohoapis.com/inventory/v1/shipmentorders
  ZOHO_INVENTORY_SHIPMENTS_URL: https://inventory.zoho.com/api/v1/shipmentorders
  ZOHO_SCOPES: ZohoInventory.items.READ,ZohoInventory.shipmentorders.READ,ZohoInventory.purchasereceives.READ,ZohoInventory.salesorders.READ
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-api-zoho-senitron-backend-api-zoho-senitron-env
  name: backend-api-zoho-senitron-env
