apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert --out .k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres-api-zoho-senitron
  name: postgres-api-zoho-senitron
spec:
  ports:
    - name: "5442"
      port: 5442
      targetPort: 5432
  selector:
    io.kompose.service: postgres-api-zoho-senitron
