services:
  aws_backend_app:
    build:
      context: ./backend_app
      dockerfile: Dockerfile.aws.backend.prod
    container_name: aws_backend_app
    restart: unless-stopped
    volumes:
      - ./backend_app:/app
      - ./backend_app/static:/app/staticfiles
    ports:
      - "8001:8001"
    networks:
      - net_api_zoho_senitron

networks:
  net_api_zoho_senitron:
    driver: bridge