services:
  backend_app:
    build:
      context: ./backend_app
      dockerfile: Dockerfile
    container_name: backend_app
    restart: unless-stopped
    volumes:
      - ./backend_app:/app
      - ./backend_app/static:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./backend_app/.env
    networks:
      - shared-network
      
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts_db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=api_zoho_senitron_qa_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - shared-network

  redis_installation:
    image: redis:latest
    container_name: redis_installation
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - shared-network

  redis_commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis_commander
    ports: ["8081:8081"]
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=channels:redis_installation:6379:6,cache:redis_installation:6379:7
    depends_on:
      - redis_installation
    networks:
      - shared-network

volumes:
  postgres_data:
  redis_data:

networks:
  shared-network:
    driver: bridge
    external: true