services:
  aws_frontend_app:
    platform: linux/amd64
    build:
      context: ./vite_react_app
      dockerfile: Dockerfile.aws.frontend.prod
    container_name: aws_frontend_app
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3030:3030"
    networks:
      - net_api_zoho_senitron
    restart: unless-stopped

networks:
  net_api_zoho_senitron:
    driver: bridge