"""
Django settings for api_project_zoho_senitron project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8=q+a0063s232#ebj-9l94lv8p+v4cb1%qh+-%su93w)4f@8w#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

env = environ.Env(
    DEBUG=(bool, True)
)

environ.Env.read_env()

ALLOWED_HOSTS = [
    'localhost', 
    '10.1.10.216', 
    '127.0.0.1', 
    'host.docker.internal', 
    'api-zoho-senitron.nws.home'
]

# Env Vars
ENVIRONMENT = env('ENVIRONMENT')
ZOHO_SCOPES = env.list('ZOHO_SCOPES', default=[])
ZOHO_INVENTORY_ITEMS_URL = env('ZOHO_INVENTORY_ITEMS_URL')
ZOHO_INVENTORY_SHIPMENTORDERS_URL = env('ZOHO_INVENTORY_SHIPMENTORDERS_URL')
ZOHO_INVENTORY_PURCHASERECEIVES_URL = env('ZOHO_INVENTORY_PURCHASERECEIVES_URL')
ZOHO_INVENTORY_SALESORDERS_URL = env('ZOHO_INVENTORY_SALESORDERS_URL')
ZOHO_INVENTORY_SHIPMENTS_URL = env('ZOHO_INVENTORY_SHIPMENTS_URL')
ZOHO_INVENTORY_PACKAGES_URL = env('ZOHO_INVENTORY_PACKAGES_URL')

DB_NAME = env('DB_NAME_DEV') if ENVIRONMENT == 'DEV' else env('DB_NAME_QA') if ENVIRONMENT == 'QA' else env('DB_NAME_PROD')
DB_USER = env('DB_USER_DEV') if ENVIRONMENT == 'DEV' else env('DB_USER_QA') if ENVIRONMENT == 'QA' else env('DB_USER_PROD')
DB_PASSWORD = env('DB_PASSWORD_DEV') if ENVIRONMENT == 'DEV' else env('DB_PASSWORD_QA') if ENVIRONMENT == 'QA' else env('DB_PASSWORD_PROD')
DB_HOST = env('DB_HOST_DEV') if ENVIRONMENT == 'DEV' else env('DB_HOST_QA') if ENVIRONMENT == 'QA' else env('DB_HOST_PROD')
DB_PORT = env('DB_PORT')
DB_ENGINE = env('DB_ENGINE')
REDIS_HOST = env('REDIS_HOST')
FRONTEND_URL = env('FRONTEND_URL_DEV') if ENVIRONMENT == 'DEV' else env('FRONTEND_URL_QA') if ENVIRONMENT == 'QA' else env('FRONTEND_URL_PROD')

# ENV VARS SENITRON
API_KEY_SENITRON = env('API_KEY_SENITRON')
API_SENITRON_QUANTITIES_URL = env('API_SENITRON_QUANTITIES_URL')
API_SENITRON_ASSETS_URL = env('API_SENITRON_ASSETS_URL')
API_SENITRON_ASSETS_LOGS_URL = env('API_SENITRON_ASSETS_LOGS_URL')

CSRF_TRUSTED_ORIGINS = [
    'https://localhost',
    'http://localhost:3039',
    'http://localhost:3030',
    'https://127.0.0.1',
    'http://127.0.0.1:3039',
    'http://127.0.0.1:3030',
    'https://host.docker.internal',
    'https://integration.nws.com',
    'https://api-zoho-senitron.nws.home'
]

CSRF_COOKIE_SECURE = False  

CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_HTTPONLY = False

CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

CSRF_COOKIE_SAMESITE = 'None'

SESSION_COOKIE_SECURE = False  

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "https://localhost",
    'http://localhost:3039',
    'http://localhost:3030',
    "https://127.0.0.1",
    "http://127.0.0.1:3039",
    "http://127.0.0.1:3030",
    "https://host.docker.internal",
    "https://integration.nws.com",
    "https://api-zoho-senitron.nws.home"
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'Accept',
    'x-requested-with',
    'accept',
    'origin',
    'user-agent',
    'dnt',
    'cache-control',
    'X-CSRFToken',
    'x-requested-with',
    'x-xsrf-token',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'graphene_django',
    'api_zoho',
    'api_senitron',
    'api_project_zoho_senitron_async_sequence',
    'django_celery_beat',
]

GRAPHENE = {
    'SCHEMA': 'api_project_zoho_senitron_graph_ql.full_schema.schema',  
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware', 
    ],
    'GRAPHIQL_ENABLED': True, 
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api_project_zoho_senitron.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, 6379)], 
        },
        'CAPACITY': 1500,
    },
}

ASGI_APPLICATION = "api_project_zoho_senitron.asgi.application"

# WSGI_APPLICATION = 'api_project_zoho_senitron.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': f'{DB_ENGINE}',
        'NAME': f'{DB_NAME}',
        'USER': f'{DB_USER}',
        'PASSWORD': f'{DB_PASSWORD}',
        'HOST': f'{DB_HOST}',
        'PORT': f'{DB_PORT}',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'api_zoho.auth_backends.LoginUserBackend', 
    'django.contrib.auth.backends.ModelBackend',
    'graphql_jwt.backends.JSONWebTokenBackend',
]

AUTH_USER_MODEL = 'api_zoho.LoginUser'


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


## Static files (CSS, JavaScript, Images)
## https://docs.djangoproject.com/en/5.0/howto/static-files/

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'
BASE_DIR_STATIC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKUP_DIR = os.path.join(BASE_DIR, 'backup')

MEDIA_URL = '/backup/'
MEDIA_ROOT = BACKUP_DIR

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB en bytes

# Celery

CELERY_BROKER_URL = 'redis://redis-api-zoho-senitron:6379/0'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_BACKEND = 'redis://redis-api-zoho-senitron:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'
CELERY_ENABLE_UTC = False

# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_BEAT_SCHEDULE = {
    'run-task-sequence-every-2-min': {
        'task': 'api_project_zoho_senitron_async_sequence.tasks.task_sequence_2_min',
        'schedule': crontab(minute='*/2', hour='7-17'),
    },
    'run-task-sequence-every-15-min': {
        'task': 'api_project_zoho_senitron_async_sequence.tasks.task_sequence_15_min',
        'schedule': crontab(minute='*/15', hour='7-17'),
    },
    'call-task-remove-old-senitron-items-assets-logs-every-day-8am': {
        'task': 'api_senitron.tasks.task_remove_old_senitron_items_assets_logs',
        'schedule': crontab(hour=8, minute=0),
    },
}
