# Generated by Django 5.0.6 on 2024-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0002_zohoinventoryitem_zohoinventoryshipmentsalesorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohoinventoryshipmentsalesorder',
            name='salesorder_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
