# Generated by Django 5.0.6 on 2024-10-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0003_alter_zohoinventoryshipmentsalesorder_salesorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohoinventoryitem',
            name='item_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
