# Generated by Django 5.0.6 on 2024-10-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0004_alter_zohoinventoryitem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoinventoryitem',
            name='synced_with_senitron',
            field=models.BooleanField(default=False),
        ),
    ]
