# Generated by Django 5.0.6 on 2024-11-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0006_loginuser_address_loginuser_city_loginuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
