# Generated by Django 5.0.6 on 2024-11-19 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0007_alter_loginuser_first_name_alter_loginuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoSkuTrackInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_tracked', models.IntegerField(default=0)),
                ('sku_matched', models.IntegerField(default=0)),
                ('sku_missing', models.IntegerField(default=0)),
                ('sku_excess', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
