# Generated by Django 5.0.6 on 2024-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0008_zohoskutrackinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoShipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_id', models.CharField(max_length=255, unique=True)),
                ('shipment_number', models.CharField(blank=True, max_length=255, null=True)),
                ('salesorder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('salesorder_number', models.CharField(blank=True, max_length=255, null=True)),
                ('associated_packages', models.CharField(blank=True, max_length=255, null=True)),
                ('is_multipiece_shipment', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_sub_status', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_charge', models.FloatField(default=0.0)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('label_format', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_time', models.DateTimeField(blank=True, null=True)),
                ('is_carrier_shipment', models.BooleanField(default=False)),
                ('is_tracked_shipment', models.BooleanField(default=False)),
                ('is_aggregator_shipment', models.BooleanField(default=False)),
                ('is_amazon_fba_shipment', models.BooleanField(default=False)),
            ],
        ),
    ]
