# Generated by Django 5.0.6 on 2024-11-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0010_zohoshipmentorder_delete_zohoshipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoPackage',
            fields=[
                ('package_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('salesorder_id', models.CharField(blank=True, max_length=50, null=True)),
                ('salesorder_number', models.CharField(blank=True, max_length=50, null=True)),
                ('salesorder_date', models.DateField(blank=True, null=True)),
                ('sales_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_channel_formatted', models.CharField(blank=True, max_length=50, null=True)),
                ('salesorder_fulfilment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_order', models.JSONField(blank=True, null=True)),
                ('package_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_method_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_link', models.URLField(blank=True, null=True)),
                ('expected_delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_delivered_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('detailed_status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_days', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_guarantee', models.BooleanField(default=False)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_persons', models.JSONField(blank=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_modified_by_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('last_modified_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('is_advanced_tracking_missing', models.BooleanField(default=False)),
                ('line_items', models.JSONField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('custom_field_hash', models.JSONField(blank=True, null=True)),
                ('shipmentorder_custom_fields', models.JSONField(blank=True, null=True)),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('picklists', models.JSONField(blank=True, null=True)),
                ('template_id', models.CharField(blank=True, max_length=50, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('template_type', models.CharField(blank=True, max_length=50, null=True)),
                ('zoho_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_zoho.zohoshipmentorder')),
            ],
        ),
    ]
