# Generated by Django 5.0.6 on 2024-11-22 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0011_zohopackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoItemAssetsTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('assets', models.JSONField(blank=True, default=list, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
