# Generated by Django 5.0.6 on 2024-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0012_zohoitemassetstrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoinventoryitem',
            name='ignore_errors',
            field=models.BooleanField(default=False),
        ),
    ]
