# Generated by Django 5.0.6 on 2024-12-02 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0013_zohoinventoryitem_ignore_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsUpdatingTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
