# Generated by Django 5.0.6 on 2024-12-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0014_jobsupdatingtimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUpdatingJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
