# Generated by Django 5.0.6 on 2024-12-05 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0015_manualupdatingjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualupdatingjobs',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
