# Generated by Django 5.2.7 on 2025-10-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_zoho', '0016_manualupdatingjobs_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zohoinventoryshipmentsalesorder',
            options={},
        ),
        migrations.AddField(
            model_name='zohoinventoryitem',
            name='item_id_int',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='zohoinventoryshipmentsalesorder',
            name='salesorder_id_int',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='zohoshipmentorder',
            name='shipment_id_int',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoitemassetstrack',
            name='item_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zohopackage',
            name='salesorder_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zohopackage',
            name='shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='zohoinventoryitem',
            index=models.Index(fields=['created_time'], name='api_zoho_zo_created_c621c5_idx'),
        ),
        migrations.AddIndex(
            model_name='zohoinventoryitem',
            index=models.Index(fields=['last_modified_time'], name='api_zoho_zo_last_mo_e2ac1b_idx'),
        ),
        migrations.AddIndex(
            model_name='zohoinventoryshipmentsalesorder',
            index=models.Index(fields=['date'], name='api_zoho_zo_date_f90e57_idx'),
        ),
        migrations.AddIndex(
            model_name='zohoinventoryshipmentsalesorder',
            index=models.Index(fields=['created_time'], name='api_zoho_zo_created_8fc74c_idx'),
        ),
        migrations.AddIndex(
            model_name='zohoitemassetstrack',
            index=models.Index(fields=['item_id', 'created_time'], name='api_zoho_zo_item_id_b0641a_idx'),
        ),
        migrations.AddIndex(
            model_name='zohopackage',
            index=models.Index(fields=['date'], name='api_zoho_zo_date_72d8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='zohoshipmentorder',
            index=models.Index(fields=['date'], name='api_zoho_zo_date_dd69c6_idx'),
        ),
        migrations.AddIndex(
            model_name='zohoshipmentorder',
            index=models.Index(fields=['created_time'], name='api_zoho_zo_created_8c3b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='zohoskutrackinfo',
            index=models.Index(fields=['date'], name='api_zoho_zo_date_0617c4_idx'),
        ),
    ]
