[supervisord]
logfile=/var/log/supervisor/supervisord.log
childlogdir=/var/log/supervisor
nodaemon=true
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

; ==== Programs ====
[program:gunicorn]
directory=/app
command=/usr/local/bin/gunicorn api_project_zoho_senitron.asgi:application --bind 0.0.0.0:8000 --workers 3 --worker-class uvicorn.workers.UvicornWorker --timeout 120 --access-logfile -
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true


[program:celery-worker]
directory=/app
command=/usr/local/bin/celery -A api_project_zoho_senitron worker --loglevel=info
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true

[program:celery-beat]
directory=/app
command=/usr/local/bin/celery -A api_project_zoho_senitron beat --loglevel=info
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
