# Generated by Django 5.0.6 on 2024-10-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenitronItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=255, unique=True)),
                ('tags_count', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SenitronStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SenitronItemAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('item_number', models.CharField(max_length=100, unique=True)),
                ('alt_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen_antenna', models.CharField(blank=True, max_length=50, null=True)),
                ('last_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('handheld_reader', models.CharField(blank=True, max_length=255, null=True)),
                ('handheld_last_seen', models.DateTimeField(blank=True, null=True)),
                ('static_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('static_zone_last_update', models.DateTimeField(blank=True, null=True)),
                ('receiving_date', models.DateTimeField(blank=True, null=True)),
                ('current_units', models.FloatField(default=0.0)),
                ('storage_unit', models.FloatField(default=0.0)),
                ('adjust_qty', models.IntegerField(default=0)),
                ('attr1', models.CharField(blank=True, max_length=255, null=True)),
                ('attr2', models.CharField(blank=True, max_length=255, null=True)),
                ('attr3', models.CharField(blank=True, max_length=255, null=True)),
                ('attr4', models.CharField(blank=True, max_length=255, null=True)),
                ('attr5', models.CharField(blank=True, max_length=255, null=True)),
                ('attr6', models.CharField(blank=True, max_length=255, null=True)),
                ('attr7', models.CharField(blank=True, max_length=255, null=True)),
                ('attr8', models.CharField(blank=True, max_length=255, null=True)),
                ('attr9', models.CharField(blank=True, max_length=255, null=True)),
                ('attr10', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epc', models.CharField(max_length=255, unique=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('senitron_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senitron_item', to='api_senitron.senitronitem')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api_senitron.senitronstatus')),
            ],
        ),
    ]
