# Generated by Django 5.0.6 on 2024-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senitronstatus',
            name='senitron_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
