# Generated by Django 5.0.6 on 2024-10-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0002_senitronstatus_senitron_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senitronitemasset',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
