# Generated by Django 5.0.6 on 2024-10-31 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0003_alter_senitronitemasset_created_at_and_more'),
        ('api_zoho', '0005_zohoinventoryitem_synced_with_senitron'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=255)),
                ('previous_stock_on_hand', models.IntegerField()),
                ('date_previous_stock_on_hand', models.DateTimeField()),
                ('actual_stock_on_hand', models.IntegerField()),
                ('date_actual_stock_on_hand', models.DateTimeField()),
                ('previous_status_zoho', models.CharField(max_length=255)),
                ('date_previous_status_zoho', models.DateTimeField()),
                ('actual_status_zoho', models.CharField(max_length=255)),
                ('date_actual_status_zoho', models.DateTimeField()),
                ('previous_quantity', models.IntegerField()),
                ('date_previous_quantity', models.DateTimeField()),
                ('actual_quantity', models.IntegerField()),
                ('date_actual_quantity', models.DateTimeField()),
                ('date_previous_status_senitron', models.DateTimeField()),
                ('date_actual_status_senitron', models.DateTimeField()),
                ('actual_status_senitron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_status_senitron', to='api_senitron.senitronstatus')),
                ('previous_status_senitron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_status_senitron', to='api_senitron.senitronstatus')),
                ('senitron_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_senitron_item', to='api_senitron.senitronitem')),
                ('zoho_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_zoho_item', to='api_zoho.zohoinventoryitem')),
            ],
        ),
    ]
