# Generated by Django 5.0.6 on 2024-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0004_timelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='actual_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='actual_status_zoho',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='actual_stock_on_hand',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_quantity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_status_senitron',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_status_zoho',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_stock_on_hand',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_quantity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_status_senitron',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_status_zoho',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_stock_on_hand',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='previous_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='previous_status_zoho',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='previous_stock_on_hand',
            field=models.IntegerField(null=True),
        ),
    ]
