# Generated by Django 5.0.6 on 2024-10-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0005_alter_timelineitem_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineitem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
