# Generated by Django 5.0.6 on 2024-11-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0006_timelineitem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='senitronitemasset',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senitronitemasset',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
