# Generated by Django 5.0.6 on 2024-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0007_senitronitemasset_date_read_senitronitemasset_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senitronitemasset',
            name='item_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
