# Generated by Django 5.0.6 on 2024-11-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0008_alter_senitronitemasset_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senitronitemasset',
            name='senitron_item',
        ),
    ]
