# Generated by Django 5.0.6 on 2024-11-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0009_remove_senitronitemasset_senitron_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='senitronitemasset',
            name='senitron_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senitron_item', to='api_senitron.senitronitem'),
        ),
    ]
