# Generated by Django 5.0.6 on 2024-11-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0010_senitronitemasset_senitron_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senitronitemasset',
            name='epc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
