# Generated by Django 5.0.6 on 2024-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0011_alter_senitronitemasset_epc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenitronItemAssetLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senitron_id', models.IntegerField(default=None, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('item_number', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('epc', models.CharField(blank=True, max_length=255, null=True)),
                ('last_status_id', models.IntegerField(null=True)),
                ('last_status_name', models.CharField(max_length=100, null=True)),
                ('current_status_id', models.IntegerField(null=True)),
                ('current_status_name', models.CharField(max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
