# Generated by Django 5.0.6 on 2024-12-05 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0012_senitronitemassetlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='senitronitemassetlogs',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
