# Generated by Django 5.0.6 on 2024-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0013_senitronitemassetlogs_created_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='senitronitemassetlogs',
            constraint=models.UniqueConstraint(fields=('serial_number', 'current_status_id', 'current_status_name', 'last_status_id', 'last_status_name', 'updated_at'), name='unique_asset_log_combination'),
        ),
    ]
