# Generated by Django 5.0.6 on 2024-12-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0017_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='load', max_length=255),
        ),
    ]
