# Generated by Django 5.2.7 on 2025-10-21 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_senitron', '0018_notification_type'),
        ('api_zoho', '0017_alter_zohoinventoryshipmentsalesorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senitronitem',
            name='item_number_int',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='module',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='username',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='first_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='item_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='senitronitemasset',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='senitronitemassetlogs',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='senitronitemassetlogs',
            name='item_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_quantity',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_status_senitron',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_status_zoho',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_actual_stock_on_hand',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_quantity',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_status_senitron',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_status_zoho',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='date_previous_stock_on_hand',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='item_number',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='senitronitem',
            index=models.Index(fields=['item_number'], name='api_senitro_item_nu_27f2af_idx'),
        ),
        migrations.AddIndex(
            model_name='senitronitemasset',
            index=models.Index(fields=['item_number', 'updated_at'], name='api_senitro_item_nu_960d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='senitronitemasset',
            index=models.Index(fields=['item_number', 'last_seen'], name='api_senitro_item_nu_5a5214_idx'),
        ),
        migrations.AddIndex(
            model_name='senitronitemassetlogs',
            index=models.Index(fields=['item_number', 'created_time'], name='api_senitro_item_nu_8eb4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='senitronstatus',
            index=models.Index(fields=['name'], name='api_senitro_name_8d7522_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineitem',
            index=models.Index(fields=['date_actual_stock_on_hand'], name='api_senitro_date_ac_00bdbb_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineitem',
            index=models.Index(fields=['date_actual_status_zoho'], name='api_senitro_date_ac_6061e2_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineitem',
            index=models.Index(fields=['date_actual_quantity'], name='api_senitro_date_ac_02c205_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineitem',
            index=models.Index(fields=['date_actual_status_senitron'], name='api_senitro_date_ac_159246_idx'),
        ),
    ]
